import { LuIndianRupee } from "react-icons/lu";
const product_card = [
  {
    id: 2,
    product_name: "Glass cleaner",
    description: "Hair-wash,jnijbpiubui cattering, ",
    price: 1000,
    currency: <LuIndianRupee />,
    cutprice: 2000,
    discount: "40%",
    thumb: "./images/allproducts (1).jpg",
  },
  {
    id: 1,
    product_name: "Floor cleaner",
    description: "Hair-wash, cattering, ",
    price: 1000,
    currency: <LuIndianRupee />,
    thumb: "./images/allproducts (2).jpg",
  },
  {
    id: 1,
    product_name: "Glass cleaner",
    description: "Hair-wash, cattering, ",
    price: 1000,
    currency: <LuIndianRupee />,
    thumb: "./images/allproducts (3).jpg",
  },
  {
    id: 1,
    product_name: "Glass cleaner",
    description: "Hair-wash, cattering, ",
    price: 1000,
    currency: <LuIndianRupee />,
    thumb: "./images/allproducts (4).jpg",
  },
  {
    id: 1,
    product_name: "Glass cleaner",
    description: "Hair-wash, cattering, ",
    price: 1000,
    currency: <LuIndianRupee />,
    thumb: "./images/allproducts (5).jpg",
  },
  {
    id: 1,
    product_name: "Glass cleaner",
    description: "Hair-wash, cattering, ",
    price: 1000,
    currency: <LuIndianRupee />,
    thumb: "./images/allproducts (6).jpg",
  },
  {
    id: 1,
    product_name: "Glass cleaner",
    description: "Hair-wash, cattering, ",
    price: 1000,
    currency: <LuIndianRupee />,
    thumb: "./images/allproducts (7).jpg",
  },
  {
    id: 1,
    product_name: "Glass cleaner",
    description: "Hair-wash, cattering, ",
    price: 1000,
    currency: <LuIndianRupee />,
    thumb: "./images/allproducts (8).jpg",
  },
  {
    id: 1,
    product_name: "Glass cleaner",
    description: "Hair-wash, cattering, ",
    price: 1000,
    currency: <LuIndianRupee />,
    thumb: "./images/allproducts (9).jpg",
  },
  {
    id: 1,
    product_name: "Glass cleaner",
    description: "Hair-wash, cattering, ",
    price: 1000,
    currency: <LuIndianRupee />,
    thumb: "./images/allproducts (10).jpg",
  },
  {
    id: 1,
    product_name: "Glass cleaner",
    description: "Hair-wash, cattering, ",
    price: 1000,
    currency: <LuIndianRupee />,
    thumb: "./images/allproducts (11).jpg",
  },
  {
    id: 1,
    product_name: "Glass cleaner",
    description: "Hair-wash, cattering, ",
    price: 1000,
    currency: <LuIndianRupee />,
    thumb: "./images/allproducts (12).jpg",
  },
  {
    id: 1,
    product_name: "Glass cleaner",
    description: "Hair-wash, cattering, ",
    price: 1000,
    currency: <LuIndianRupee />,
    thumb: "./images/allproducts (13).jpg",
  },
  {
    id: 1,
    product_name: "Glass cleaner",
    description: "Hair-wash, cattering, ",
    price: 1000,
    currency: <LuIndianRupee />,
    thumb: "./images/allproducts (14).jpg",
  },
  {
    id: 1,
    product_name: "Glass cleaner",
    description: "Hair-wash, cattering, ",
    price: 1000,
    currency: <LuIndianRupee />,
    thumb: "./images/allproducts (15).jpg",
  },
  {
    id: 1,
    product_name: "Glass cleaner",
    description: "Hair-wash, cattering, ",
    price: 1000,
    currency: <LuIndianRupee />,
    thumb: "./images/allproducts (16).jpg",
  },
];

export default product_card;
